# Generated by Django 3.1.5 on 2021-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank='true', null='true', upload_to='Flavor')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='chocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Product')),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('Ingredients', models.TextField()),
                ('flavor', models.ManyToManyField(to='cacaoville.flavor', verbose_name='flavor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
