# Generated by Django 3.1.5 on 2021-01-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoville', '0003_auto_20210130_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank='true', null='true', upload_to='Flavor')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.RemoveField(
            model_name='chocolate',
            name='flavour',
        ),
        migrations.DeleteModel(
            name='flavour',
        ),
        migrations.AddField(
            model_name='chocolate',
            name='flavor',
            field=models.ManyToManyField(to='cacaoville.flavor', verbose_name='flavor'),
        ),
    ]
