# Generated by Django 3.1.5 on 2021-01-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoville', '0005_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='abouts',
        ),
    ]
